"""change the column name

Revision ID: 74f03ec35944
Revises: eacc3f0bda9d
Create Date: 2026-03-26 01:12:29.458130

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '74f03ec35944'
down_revision: Union[str, Sequence[str], None] = 'eacc3f0bda9d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todos', sa.Column('status', sa.DateTime(), nullable=True))
    op.drop_column('todos', 'credit_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todos', sa.Column('credit_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('todos', 'status')
    # ### end Alembic commands ###
