"""add name and email to students

Revision ID: b8b38ce9d395
Revises: d03552bd8c87
Create Date: 2026-04-19 03:46:03.193175

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b8b38ce9d395'
down_revision: Union[str, Sequence[str], None] = 'd03552bd8c87'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('name', sa.String(), nullable=True))
    op.add_column('students', sa.Column('email', sa.String(), nullable=True))
    # Update existing rows with data from users table
    op.execute("""
        UPDATE students
        SET name = users.name, email = users.email
        FROM users
        WHERE students.user_id = users.id
    """)
    # Now make them not null
    op.alter_column('students', 'name', nullable=False)
    op.alter_column('students', 'email', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('students', 'email')
    op.drop_column('students', 'name')
    # ### end Alembic commands ###
