"""add name and email to teachers

Revision ID: cc581a55f05c
Revises: 391355a4b2e9
Create Date: 2026-04-19 03:54:23.410384

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cc581a55f05c'
down_revision: Union[str, Sequence[str], None] = '391355a4b2e9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teachers', sa.Column('name', sa.String(), nullable=True))
    op.add_column('teachers', sa.Column('email', sa.String(), nullable=True))
    # Update existing rows with data from users table
    op.execute("""
        UPDATE teachers
        SET name = users.name, email = users.email
        FROM users
        WHERE teachers.user_id = users.id
    """)
    # Now make them not null
    op.alter_column('teachers', 'name', nullable=False)
    op.alter_column('teachers', 'email', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('teachers', 'email')
    op.drop_column('teachers', 'name')
    # ### end Alembic commands ###
